In [30]:
import pandas as pd

In [31]:
# # Load the full dataset (replace with your actual full data file path)
# full_data_path = 'US_Accidents_March23.csv'
# df = pd.read_csv(full_data_path)

# # Check total rows available
# print(f"Total rows in full data: {len(df)}")

# # Sample 1 million rows (or all if dataset smaller)
# sample_size = min(1_000_000, len(df))
# df_sampled = df.sample(n=sample_size, random_state=42)  # random_state for reproducibility

# # Optional: reset index
# df_sampled.reset_index(drop=True, inplace=True)

# # Save sampled data
# output_path = 'US_Accidents_March23_sampled_1M.csv'
# df_sampled.to_csv(output_path, index=False)

# print(f"Sampled {sample_size} rows saved to {output_path}")

In [32]:
df = pd.read_csv('US_Accidents_March23_sampled_1M.csv')
df.head()

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-7182628,Source1,1,2020-04-17 09:29:30,2020-04-17 10:29:30,26.706900,-80.119360,26.706900,-80.119360,0.000,...,False,False,False,False,True,False,Day,Day,Day,Day
1,A-5404588,Source1,2,2022-04-21 10:01:00.000000000,2022-04-21 11:44:08.000000000,38.781024,-121.265820,38.780377,-121.265815,0.045,...,False,False,True,False,False,False,Day,Day,Day,Day
2,A-156000,Source3,3,2016-08-12 16:45:00,2016-08-12 17:15:00,33.985249,-84.269348,NaN,NaN,0.000,...,False,False,False,False,False,False,Day,Day,Day,Day
3,A-1871277,Source2,3,2019-09-20 15:22:16,2019-09-20 15:56:00,47.118706,-122.556908,NaN,NaN,0.000,...,False,False,False,False,False,False,Day,Day,Day,Day
4,A-2031222,Source2,2,2019-06-03 16:55:43,2019-06-03 18:12:09,33.451355,-111.890343,NaN,NaN,0.000,...,False,False,False,False,False,False,Day,Day,Day,Day

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 46 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   ID                     1000000 non-null  object
 1   Source                 1000000 non-null  object
 2   Severity               1000000 non-null  int64
 3   Start_Time             1000000 non-null  object
 4   End_Time               1000000 non-null  object
 5   Start_Lat              1000000 non-null  float64
 6   Start_Lng              1000000 non-null  float64
 7   End_Lat                559358 non-null   float64
 8   End_Lng                559358 non-null   float64
 9   Distance(mi)           1000000 non-null  float64
 10  Description            999999 non-null   object
 11  Street                 998593 non-null   object
 12  City                   999964 non-null   object
 13  County                 1000000 non-null  object
 14  State                  1000000 non-null  object
 15  Zipcode                999755 non-null   object
 16  Country                1000000 non-null  object
 17  Timezone               999007 non-null   object
 18  Airport_Code           997099 non-null   object
 19  Weather_Timestamp      984422 non-null   object
 20  Temperature(F)         978811 non-null   float64
 21  Wind_Chill(F)          741085 non-null   float64
 22  Humidity(%)            977513 non-null   float64
 23  Pressure(in)           981780 non-null   float64
 24  Visibility(mi)         977075 non-null   float64
 25  Wind_Direction         977182 non-null   object
 26  Wind_Speed(mph)        925598 non-null   float64
 27  Precipitation(in)      714393 non-null   float64
 28  Weather_Condition      977560 non-null   object
 29  Amenity                1000000 non-null  bool
 30  Bump                   1000000 non-null  bool
 31  Crossing               1000000 non-null  bool
 32  Give_Way               1000000 non-null  bool
 33  Junction               1000000 non-null  bool
 34  No_Exit                1000000 non-null  bool
 35  Railway                1000000 non-null  bool
 36  Roundabout             1000000 non-null  bool
 37  Station                1000000 non-null  bool
 38  Stop                   1000000 non-null  bool
 39  Traffic_Calming        1000000 non-null  bool
 40  Traffic_Signal         1000000 non-null  bool
 41  Turning_Loop           1000000 non-null  bool
 42  Sunrise_Sunset         996913 non-null   object
 43  Civil_Twilight         996913 non-null   object
 44  Nautical_Twilight      996913 non-null   object
 45  Astronomical_Twilight  996913 non-null   object
dtypes: bool(13), float64(12), int64(1), object(20)
memory usage: 264.2+ MB

In [34]:
(df.isnull().sum() / df.shape[0])*100

ID                        0.0000
Source                    0.0000
Severity                  0.0000
Start_Time                0.0000
End_Time                  0.0000
Start_Lat                 0.0000
Start_Lng                 0.0000
End_Lat                  44.0642
End_Lng                  44.0642
Distance(mi)              0.0000
Description               0.0001
Street                    0.1407
City                      0.0036
County                    0.0000
State                     0.0000
Zipcode                   0.0245
Country                   0.0000
Timezone                  0.0993
Airport_Code              0.2901
Weather_Timestamp         1.5578
Temperature(F)            2.1189
Wind_Chill(F)            25.8915
Humidity(%)               2.2487
Pressure(in)              1.8220
Visibility(mi)            2.2925
Wind_Direction            2.2818
Wind_Speed(mph)           7.4402
Precipitation(in)        28.5607
Weather_Condition         2.2440
Amenity                   0.0000
Bump                      0.0000
Crossing                  0.0000
Give_Way                  0.0000
Junction                  0.0000
No_Exit                   0.0000
Railway                   0.0000
Roundabout                0.0000
Station                   0.0000
Stop                      0.0000
Traffic_Calming           0.0000
Traffic_Signal            0.0000
Turning_Loop              0.0000
Sunrise_Sunset            0.3087
Civil_Twilight            0.3087
Nautical_Twilight         0.3087
Astronomical_Twilight     0.3087
dtype: float64

In [35]:
df.columns

Index(['ID', 'Source', 'Severity', 'Start_Time', 'End_Time', 'Start_Lat',
       'Start_Lng', 'End_Lat', 'End_Lng', 'Distance(mi)', 'Description',
       'Street', 'City', 'County', 'State', 'Zipcode', 'Country', 'Timezone',
       'Airport_Code', 'Weather_Timestamp', 'Temperature(F)', 'Wind_Chill(F)',
       'Humidity(%)', 'Pressure(in)', 'Visibility(mi)', 'Wind_Direction',
       'Wind_Speed(mph)', 'Precipitation(in)', 'Weather_Condition', 'Amenity',
       'Bump', 'Crossing', 'Give_Way', 'Junction', 'No_Exit', 'Railway',
       'Roundabout', 'Station', 'Stop', 'Traffic_Calming', 'Traffic_Signal',
       'Turning_Loop', 'Sunrise_Sunset', 'Civil_Twilight', 'Nautical_Twilight',
       'Astronomical_Twilight'],
      dtype='object')

In [36]:
# Drop the columns of 'End_Lat', 'End_Lng'
df = df.drop(columns=['End_Lat', 'End_Lng'])

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 44 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   ID                     1000000 non-null  object
 1   Source                 1000000 non-null  object
 2   Severity               1000000 non-null  int64
 3   Start_Time             1000000 non-null  object
 4   End_Time               1000000 non-null  object
 5   Start_Lat              1000000 non-null  float64
 6   Start_Lng              1000000 non-null  float64
 7   Distance(mi)           1000000 non-null  float64
 8   Description            999999 non-null   object
 9   Street                 998593 non-null   object
 10  City                   999964 non-null   object
 11  County                 1000000 non-null  object
 12  State                  1000000 non-null  object
 13  Zipcode                999755 non-null   object
 14  Country                1000000 non-null  object
 15  Timezone               999007 non-null   object
 16  Airport_Code           997099 non-null   object
 17  Weather_Timestamp      984422 non-null   object
 18  Temperature(F)         978811 non-null   float64
 19  Wind_Chill(F)          741085 non-null   float64
 20  Humidity(%)            977513 non-null   float64
 21  Pressure(in)           981780 non-null   float64
 22  Visibility(mi)         977075 non-null   float64
 23  Wind_Direction         977182 non-null   object
 24  Wind_Speed(mph)        925598 non-null   float64
 25  Precipitation(in)      714393 non-null   float64
 26  Weather_Condition      977560 non-null   object
 27  Amenity                1000000 non-null  bool
 28  Bump                   1000000 non-null  bool
 29  Crossing               1000000 non-null  bool
 30  Give_Way               1000000 non-null  bool
 31  Junction               1000000 non-null  bool
 32  No_Exit                1000000 non-null  bool
 33  Railway                1000000 non-null  bool
 34  Roundabout             1000000 non-null  bool
 35  Station                1000000 non-null  bool
 36  Stop                   1000000 non-null  bool
 37  Traffic_Calming        1000000 non-null  bool
 38  Traffic_Signal         1000000 non-null  bool
 39  Turning_Loop           1000000 non-null  bool
 40  Sunrise_Sunset         996913 non-null   object
 41  Civil_Twilight         996913 non-null   object
 42  Nautical_Twilight      996913 non-null   object
 43  Astronomical_Twilight  996913 non-null   object
dtypes: bool(13), float64(10), int64(1), object(20)
memory usage: 248.9+ MB

In [38]:
# Convert the 'Start_Time' and 'End_Time' columns to datetime format
df['Start_Time'] = pd.to_datetime(df['Start_Time'], format='mixed')
df['End_Time'] = pd.to_datetime(df['End_Time'], format='mixed')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 44 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   ID                     1000000 non-null  object
 1   Source                 1000000 non-null  object
 2   Severity               1000000 non-null  int64
 3   Start_Time             1000000 non-null  datetime64[ns]
 4   End_Time               1000000 non-null  datetime64[ns]
 5   Start_Lat              1000000 non-null  float64
 6   Start_Lng              1000000 non-null  float64
 7   Distance(mi)           1000000 non-null  float64
 8   Description            999999 non-null   object
 9   Street                 998593 non-null   object
 10  City                   999964 non-null   object
 11  County                 1000000 non-null  object
 12  State                  1000000 non-null  object
 13  Zipcode                999755 non-null   object
 14  Country                1000000 non-null  object
 15  Timezone               999007 non-null   object
 16  Airport_Code           997099 non-null   object
 17  Weather_Timestamp      984422 non-null   object
 18  Temperature(F)         978811 non-null   float64
 19  Wind_Chill(F)          741085 non-null   float64
 20  Humidity(%)            977513 non-null   float64
 21  Pressure(in)           981780 non-null   float64
 22  Visibility(mi)         977075 non-null   float64
 23  Wind_Direction         977182 non-null   object
 24  Wind_Speed(mph)        925598 non-null   float64
 25  Precipitation(in)      714393 non-null   float64
 26  Weather_Condition      977560 non-null   object
 27  Amenity                1000000 non-null  bool
 28  Bump                   1000000 non-null  bool
 29  Crossing               1000000 non-null  bool
 30  Give_Way               1000000 non-null  bool
 31  Junction               1000000 non-null  bool
 32  No_Exit                1000000 non-null  bool
 33  Railway                1000000 non-null  bool
 34  Roundabout             1000000 non-null  bool
 35  Station                1000000 non-null  bool
 36  Stop                   1000000 non-null  bool
 37  Traffic_Calming        1000000 non-null  bool
 38  Traffic_Signal         1000000 non-null  bool
 39  Turning_Loop           1000000 non-null  bool
 40  Sunrise_Sunset         996913 non-null   object
 41  Civil_Twilight         996913 non-null   object
 42  Nautical_Twilight      996913 non-null   object
 43  Astronomical_Twilight  996913 non-null   object
dtypes: bool(13), datetime64[ns](2), float64(10), int64(1), object(18)
memory usage: 248.9+ MB

In [39]:
# Convert coordinates to numeric (if not already)
df['Start_Lat'] = pd.to_numeric(df['Start_Lat'], errors='coerce')
df['Start_Lng'] = pd.to_numeric(df['Start_Lng'], errors='coerce')

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 44 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   ID                     1000000 non-null  object
 1   Source                 1000000 non-null  object
 2   Severity               1000000 non-null  int64
 3   Start_Time             1000000 non-null  datetime64[ns]
 4   End_Time               1000000 non-null  datetime64[ns]
 5   Start_Lat              1000000 non-null  float64
 6   Start_Lng              1000000 non-null  float64
 7   Distance(mi)           1000000 non-null  float64
 8   Description            999999 non-null   object
 9   Street                 998593 non-null   object
 10  City                   999964 non-null   object
 11  County                 1000000 non-null  object
 12  State                  1000000 non-null  object
 13  Zipcode                999755 non-null   object
 14  Country                1000000 non-null  object
 15  Timezone               999007 non-null   object
 16  Airport_Code           997099 non-null   object
 17  Weather_Timestamp      984422 non-null   object
 18  Temperature(F)         978811 non-null   float64
 19  Wind_Chill(F)          741085 non-null   float64
 20  Humidity(%)            977513 non-null   float64
 21  Pressure(in)           981780 non-null   float64
 22  Visibility(mi)         977075 non-null   float64
 23  Wind_Direction         977182 non-null   object
 24  Wind_Speed(mph)        925598 non-null   float64
 25  Precipitation(in)      714393 non-null   float64
 26  Weather_Condition      977560 non-null   object
 27  Amenity                1000000 non-null  bool
 28  Bump                   1000000 non-null  bool
 29  Crossing               1000000 non-null  bool
 30  Give_Way               1000000 non-null  bool
 31  Junction               1000000 non-null  bool
 32  No_Exit                1000000 non-null  bool
 33  Railway                1000000 non-null  bool
 34  Roundabout             1000000 non-null  bool
 35  Station                1000000 non-null  bool
 36  Stop                   1000000 non-null  bool
 37  Traffic_Calming        1000000 non-null  bool
 38  Traffic_Signal         1000000 non-null  bool
 39  Turning_Loop           1000000 non-null  bool
 40  Sunrise_Sunset         996913 non-null   object
 41  Civil_Twilight         996913 non-null   object
 42  Nautical_Twilight      996913 non-null   object
 43  Astronomical_Twilight  996913 non-null   object
dtypes: bool(13), datetime64[ns](2), float64(10), int64(1), object(18)
memory usage: 248.9+ MB

In [41]:
(df.isnull().sum() / df.shape[0])*100

ID                        0.0000
Source                    0.0000
Severity                  0.0000
Start_Time                0.0000
End_Time                  0.0000
Start_Lat                 0.0000
Start_Lng                 0.0000
Distance(mi)              0.0000
Description               0.0001
Street                    0.1407
City                      0.0036
County                    0.0000
State                     0.0000
Zipcode                   0.0245
Country                   0.0000
Timezone                  0.0993
Airport_Code              0.2901
Weather_Timestamp         1.5578
Temperature(F)            2.1189
Wind_Chill(F)            25.8915
Humidity(%)               2.2487
Pressure(in)              1.8220
Visibility(mi)            2.2925
Wind_Direction            2.2818
Wind_Speed(mph)           7.4402
Precipitation(in)        28.5607
Weather_Condition         2.2440
Amenity                   0.0000
Bump                      0.0000
Crossing                  0.0000
Give_Way                  0.0000
Junction                  0.0000
No_Exit                   0.0000
Railway                   0.0000
Roundabout                0.0000
Station                   0.0000
Stop                      0.0000
Traffic_Calming           0.0000
Traffic_Signal            0.0000
Turning_Loop              0.0000
Sunrise_Sunset            0.3087
Civil_Twilight            0.3087
Nautical_Twilight         0.3087
Astronomical_Twilight     0.3087
dtype: float64

In [42]:
df.columns

Index(['ID', 'Source', 'Severity', 'Start_Time', 'End_Time', 'Start_Lat',
       'Start_Lng', 'Distance(mi)', 'Description', 'Street', 'City', 'County',
       'State', 'Zipcode', 'Country', 'Timezone', 'Airport_Code',
       'Weather_Timestamp', 'Temperature(F)', 'Wind_Chill(F)', 'Humidity(%)',
       'Pressure(in)', 'Visibility(mi)', 'Wind_Direction', 'Wind_Speed(mph)',
       'Precipitation(in)', 'Weather_Condition', 'Amenity', 'Bump', 'Crossing',
       'Give_Way', 'Junction', 'No_Exit', 'Railway', 'Roundabout', 'Station',
       'Stop', 'Traffic_Calming', 'Traffic_Signal', 'Turning_Loop',
       'Sunrise_Sunset', 'Civil_Twilight', 'Nautical_Twilight',
       'Astronomical_Twilight'],
      dtype='object')

In [43]:
# Drop the rows with missing values except some columns.
df = df.dropna(subset=['ID', 'Source', 'Severity', 'Start_Time', 'End_Time', 'Start_Lat',
       'Start_Lng', 'Distance(mi)', 'Description', 'Street', 'City', 'County',
       'State', 'Zipcode', 'Country', 'Timezone', 'Airport_Code',
       'Weather_Timestamp', 'Temperature(F)', 'Humidity(%)',
       'Pressure(in)', 'Visibility(mi)', 'Wind_Direction','Weather_Condition', 'Amenity', 'Bump', 'Crossing',
       'Give_Way', 'Junction', 'No_Exit', 'Railway', 'Roundabout', 'Station',
       'Stop', 'Traffic_Calming', 'Traffic_Signal', 'Turning_Loop',
       'Sunrise_Sunset', 'Civil_Twilight', 'Nautical_Twilight',
       'Astronomical_Twilight'])

In [44]:
(df.isnull().sum() / df.shape[0])*100

ID                        0.000000
Source                    0.000000
Severity                  0.000000
Start_Time                0.000000
End_Time                  0.000000
Start_Lat                 0.000000
Start_Lng                 0.000000
Distance(mi)              0.000000
Description               0.000000
Street                    0.000000
City                      0.000000
County                    0.000000
State                     0.000000
Zipcode                   0.000000
Country                   0.000000
Timezone                  0.000000
Airport_Code              0.000000
Weather_Timestamp         0.000000
Temperature(F)            0.000000
Wind_Chill(F)            23.854236
Humidity(%)               0.000000
Pressure(in)              0.000000
Visibility(mi)            0.000000
Wind_Direction            0.000000
Wind_Speed(mph)           5.089997
Precipitation(in)        27.520515
Weather_Condition         0.000000
Amenity                   0.000000
Bump                      0.000000
Crossing                  0.000000
Give_Way                  0.000000
Junction                  0.000000
No_Exit                   0.000000
Railway                   0.000000
Roundabout                0.000000
Station                   0.000000
Stop                      0.000000
Traffic_Calming           0.000000
Traffic_Signal            0.000000
Turning_Loop              0.000000
Sunrise_Sunset            0.000000
Civil_Twilight            0.000000
Nautical_Twilight         0.000000
Astronomical_Twilight     0.000000
dtype: float64

### Task: Impute the columns ['Wind_Speed(mph)', 'Precipitation(in)','Wind_Chill(F)'] with suitable imputation technique.